# Generated by Django 5.0.7 on 2024-09-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_welcomedestination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationimage',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_images',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='destinations.destinationimage'),
        ),
    ]
