# Generated by Django 5.0.7 on 2024-09-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_destinationimage_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='destination_images',
        ),
        migrations.DeleteModel(
            name='DestinationImage',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_images',
            field=models.ImageField(blank=True, null=True, upload_to='destination_images/'),
        ),
    ]
